In [2]:
import pandas as pd
import numpy as np
from google.colab import drive

In [3]:
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
data = pd.read_csv('/content/drive/MyDrive/Data/IRIS.csv')

In [6]:
data.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [53]:
features = data.drop(['species'], axis = 1)
label = data[['species']]


In [41]:
features = features.to_numpy()
features.shape

(150, 4)

In [42]:
features_new = np.insert(features, 0, 1, axis=1)
features_new.shape

(150, 5)

In [14]:
val = list(label['species'].unique())
val

['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']

In [107]:
one_hot_encoded_data = np.asarray(pd.get_dummies(label, columns = ['species']))

In [108]:
label.drop(['species'], axis=1)
label = one_hot_encoded_data

In [43]:
np.random.seed(42)
weights =  np.random.rand(5,3)
weights

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497]])

In [45]:
z = np.dot(features_new,weights)
z.shape

(150, 3)

In [46]:
z[0]

array([4.78878117, 4.849312  , 5.02570732])

In [116]:
features_new.shape

(150, 5)

In [70]:
y_hat = np.exp(z[0])/ np.sum(np.exp(z[0]))
y_hat

array([0.30032304, 0.3190633 , 0.38061366])

In [88]:
features_new.shape

(150, 5)

In [124]:
weights

array([[0.37250406, 0.95296173, 0.73178258],
       [0.58283796, 0.17029177, 0.15754191],
       [0.05350014, 0.87172262, 0.600152  ],
       [0.68995969, 0.03297883, 0.97562841],
       [0.82562302, 0.21640149, 0.1845822 ]])

In [89]:
num = np.exp(np.dot(features_new,weights))
num.shape

(150, 3)

In [98]:
den = np.sum(num, axis=1)

In [102]:
den = den.reshape(den.shape[0],1)

In [103]:

y_hat = num/den

In [132]:
label[1]*y_hat[1]

array([0.89296434, 0.        , 0.        ])

In [ ]:
y_hat

In [114]:
## Loss Function

loss = -np.mean(np.sum(label*np.log(y_hat)))
loss

320.8076054958709

In [120]:
## Backpropogation

dw = 1/features_new.shape[0] * (np.dot(features_new.T, (y_hat - label) ))
print(dw.shape)
print(features_new.shape)
print(y_hat.shape)
print(weights.shape)

(5, 3)
(150, 5)
(150, 3)
(5, 3)


In [121]:
alpha = 0.1
weights-=alpha * dw

In [123]:
weights

array([[0.37250406, 0.95296173, 0.73178258],
       [0.58283796, 0.17029177, 0.15754191],
       [0.05350014, 0.87172262, 0.600152  ],
       [0.68995969, 0.03297883, 0.97562841],
       [0.82562302, 0.21640149, 0.1845822 ]])

In [138]:
np.sum(label*np.log(y_hat), axis=1)

array([-7.61103089e-04, -4.23224436e-03, -1.75895564e-03, -6.77496884e-03,
       -6.21430890e-04, -6.27567937e-04, -1.62043723e-03, -1.82920625e-03,
       -9.44832214e-03, -5.27057963e-03, -4.92984810e-04, -3.58798642e-03,
       -4.91591302e-03, -1.96502962e-03, -3.20730753e-05, -3.95262122e-05,
       -9.44086164e-05, -7.24284085e-04, -6.60690552e-04, -4.68267873e-04,
       -3.15354823e-03, -6.03452283e-04, -1.39730270e-04, -4.97068156e-03,
       -1.47737852e-02, -9.84224270e-03, -2.65881800e-03, -1.10514815e-03,
       -9.32153246e-04, -7.26327374e-03, -8.88914241e-03, -1.10860330e-03,
       -1.88295243e-04, -6.09528908e-05, -5.27057963e-03, -8.10683174e-04,
       -3.17168989e-04, -5.27057963e-03, -4.35562156e-03, -1.65447856e-03,
       -4.98776726e-04, -3.09120483e-02, -2.37705421e-03, -1.77858358e-03,
       -2.95920917e-03, -4.45266259e-03, -7.90056666e-04, -3.12097091e-03,
       -5.45081838e-04, -1.54295797e-03, -2.06303963e-03, -7.36301601e-03,
       -1.25817207e-02, -

In [156]:
alpha = 0.1
np.random.seed(42)
weights =  np.random.rand(5,3)
for i in range(1000):
  z = np.dot(features_new,weights)
  num = np.exp(np.dot(features_new,weights))
  den = np.sum(num, axis=1)
  den = den.reshape(den.shape[0],1)
  y_hat = num/den
  loss = -np.mean(np.sum(label*np.log(y_hat), axis=1))
  print('Epoch: '+str(i+1)+" Loss: "+str(loss))
  dw = 1/features_new.shape[0] * (np.dot(features_new.T, (y_hat - label) ))
  weights-=alpha * dw

Epoch: 1 Loss: 2.138717369972473
Epoch: 2 Loss: 1.690668163137116
Epoch: 3 Loss: 1.555975299825662
Epoch: 4 Loss: 1.4198174001142927
Epoch: 5 Loss: 1.3130903120709756
Epoch: 6 Loss: 1.2136167326220746
Epoch: 7 Loss: 1.1337283921248626
Epoch: 8 Loss: 1.0564937144243742
Epoch: 9 Loss: 0.9959368354757258
Epoch: 10 Loss: 0.9404930470317572
Epoch: 11 Loss: 0.896323493157635
Epoch: 12 Loss: 0.8634905522034996
Epoch: 13 Loss: 0.8298091650556296
Epoch: 14 Loss: 0.8181397554471763
Epoch: 15 Loss: 0.787919498864809
Epoch: 16 Loss: 0.7939473836593867
Epoch: 17 Loss: 0.7609768421572891
Epoch: 18 Loss: 0.7804126680203869
Epoch: 19 Loss: 0.7407847442654796
Epoch: 20 Loss: 0.7694100360783076
Epoch: 21 Loss: 0.7229717395697309
Epoch: 22 Loss: 0.7577548908818994
Epoch: 23 Loss: 0.7066090699529519
Epoch: 24 Loss: 0.745748592465384
Epoch: 25 Loss: 0.6917802170272093
Epoch: 26 Loss: 0.7341473865725541
Epoch: 27 Loss: 0.6784317667278597
Epoch: 28 Loss: 0.7232302000232318
Epoch: 29 Loss: 0.6663606237655606


## Prediction

In [157]:
x_test = np.asarray([1, 5.1,	3.5,	1.4,	0.2])

In [158]:
z = np.dot(weights.T, x_test)
num = np.exp(z)
den = np.sum(num)
y_hat = num/den

In [159]:
y_hat

array([9.91260390e-01, 8.73960525e-03, 4.73932712e-09])